builders:
  material_icons_mapper:
    import: "package:icon_data_parser/src/icon_builder/builder.dart"
    builder_factories: ["materialIconsMapperBuilder"]
    build_extensions:
      r"$lib$":
        - "icon_maps/material_icons_mapper.g.dart"
        - "icon_maps/material_icon_data_map.g.dart"
    auto_apply: root_package
    build_to: source
    applies_builders: []



# To generate icons data mapper, Run this command on the project terminal
#flutter pub run build_runner clean
#flutter pub run build_runner build --delete-conflicting-outputs
